"use client";

import { useEffect, useMemo, useState } from "react";
import {
  Area,
  AreaChart,
  Bar,
  BarChart,
  CartesianGrid,
  Cell,
  Pie,
  PieChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis
} from "recharts";
import {
  Activity,
  AlertTriangle,
  ArrowDownRight,
  ArrowUpRight,
  BriefcaseBusiness,
  CalendarClock,
  CheckCircle2,
  CircleDollarSign,
  Minus,
  RefreshCw,
  Sparkles,
  Target,
  Wallet
} from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import {
  buildInfrastructureStatusData,
  buildLeadStatusData,
  buildMonthlyRevenue,
  buildRevenueByCategory,
  buildServiceDemandData,
  buildTeamCapacityData
} from "@/lib/analytics";
import { readMeetHistory, type MeetSessionRecord } from "@/lib/meet-session-store";
import { useBusinessStore } from "@/lib/store";
import { cn, formatCurrency } from "@/lib/utils";

const COLORS = ["#0f766e", "#2563eb", "#7c3aed", "#d97706", "#dc2626", "#0891b2"];
const assistantWeekdays = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"] as const;
const assistantWeekdayShortLabels: Record<(typeof assistantWeekdays)[number], string> = {
  monday: "Mon",
  tuesday: "Tue",
  wednesday: "Wed",
  thursday: "Thu",
  friday: "Fri",
  saturday: "Sat",
  sunday: "Sun"
};
const AUTO_SYNC_REVENUE_SOURCES = new Set(["project_income_sync", "project_value_sync", "project_pending_sync"]);

function normalizeRevenueText(value: unknown) {
  return String(value ?? "").toLowerCase().replace(/[^a-z0-9]/g, "");
}

function isAutoRevenueSummaryRow(row: Record<string, unknown>) {
  const syncSource = String(row.syncSource ?? "");
  if (AUTO_SYNC_REVENUE_SOURCES.has(syncSource)) return true;

  const sourceName = normalizeRevenueText(row.sourceName);
  const category = normalizeRevenueText(row.category);
  const remarks = normalizeRevenueText(row.remarks);
  const paymentMode = normalizeRevenueText(row.paymentMode);

  return (
    paymentMode === "auto" ||
    ["projectvaluesnapshot", "projectsreceivedtilldate", "pendingprojectcollections"].includes(sourceName) ||
    ["projectpipeline", "projectreceipts", "pendingcollections"].includes(category) ||
    remarks.includes("autogeneratedfromallprojectvalues") ||
    remarks.includes("autogeneratedfromprojectamountreceived") ||
    remarks.includes("autogeneratedfromprojectpendingamounts")
  );
}

const tooltipStyle = {
  border: "1px solid rgba(148,163,184,0.18)",
  borderRadius: 18,
  background: "rgba(255,255,255,0.97)",
  color: "#0f172a",
  boxShadow: "0 20px 60px rgba(15,23,42,0.12)"
};

function formatNumber(value: number) {
  return new Intl.NumberFormat("en-IN").format(Math.round(value));
}

function percent(numerator: number, denominator: number) {
  if (!denominator) return 0;
  return Math.round((numerator / denominator) * 100);
}

type DashboardTab = "revenue" | "sales" | "operations" | "infrastructure";

function startOfDay(date: Date) {
  return new Date(date.getFullYear(), date.getMonth(), date.getDate());
}

function addDays(date: Date, days: number) {
  const next = new Date(date);
  next.setDate(next.getDate() + days);
  return next;
}

function isInRange(dateText: string | null | undefined, from: Date, to: Date) {
  if (!dateText) return false;
  const date = new Date(dateText);
  if (Number.isNaN(date.getTime())) return false;
  return date >= from && date < to;
}

function getTrend(current: number, previous: number, positiveWhenUp = true) {
  const delta = current - previous;
  const direction = delta === 0 ? "flat" : delta > 0 ? "up" : "down";
  const tone =
    direction === "flat"
      ? "text-slate-500 dark:text-zinc-400"
      : positiveWhenUp
        ? direction === "up"
          ? "text-emerald-600 dark:text-emerald-300"
          : "text-rose-600 dark:text-rose-300"
        : direction === "up"
          ? "text-rose-600 dark:text-rose-300"
          : "text-emerald-600 dark:text-emerald-300";

  return {
    delta,
    direction,
    tone,
    label: `${delta > 0 ? "+" : ""}${formatNumber(delta)} vs last week`
  };
}

function ComparisonCard({
  label,
  value,
  helper,
  trend
}: {
  label: string;
  value: string;
  helper: string;
  trend: ReturnType<typeof getTrend>;
}) {
  const TrendIcon = trend.direction === "up" ? ArrowUpRight : trend.direction === "down" ? ArrowDownRight : Minus;

  return (
    <div className="rounded-[24px] border border-slate-200/80 bg-white/88 p-4 shadow-sm dark:border-white/10 dark:bg-white/[0.03]">
      <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-500 dark:text-zinc-500">{label}</p>
      <p className="mt-3 text-3xl font-semibold tracking-tight text-slate-950 dark:text-white">{value}</p>
      <div className="mt-3 flex items-center justify-between gap-3">
        <p className="text-xs text-slate-500 dark:text-zinc-400">{helper}</p>
        <span className={cn("inline-flex items-center gap-1 text-xs font-semibold", trend.tone)}>
          <TrendIcon className="h-3.5 w-3.5" />
          {trend.label}
        </span>
      </div>
    </div>
  );
}

function EmptyVisual({ label }: { label: string }) {
  return (
    <div className="flex h-full min-h-[220px] items-center justify-center rounded-[28px] border border-dashed border-slate-200 bg-slate-50/70 text-sm text-slate-500 dark:border-white/10 dark:bg-white/[0.03] dark:text-zinc-400">
      {label}
    </div>
  );
}

function SectionCard({
  title,
  subtitle,
  children,
  className,
  action
}: {
  title: string;
  subtitle?: string;
  children: React.ReactNode;
  className?: string;
  action?: React.ReactNode;
}) {
  return (
    <Card
      className={cn(
        "rounded-[32px] border border-slate-200/80 bg-white/92 p-5 shadow-[0_24px_80px_rgba(15,23,42,0.08)] dark:border-white/10 dark:bg-slate-950/70",
        className
      )}
    >
      <div className="mb-5 flex items-start justify-between gap-4">
        <div>
          <p className="text-sm font-semibold text-slate-900 dark:text-white">{title}</p>
          {subtitle ? <p className="mt-1 text-xs leading-6 text-slate-500 dark:text-zinc-400">{subtitle}</p> : null}
        </div>
        {action}
      </div>
      {children}
    </Card>
  );
}

function HeroMetric({
  label,
  value,
  helper,
  accent
}: {
  label: string;
  value: string;
  helper: string;
  accent: string;
}) {
  return (
    <div className="rounded-[26px] border border-white/70 bg-white/70 p-4 shadow-sm backdrop-blur-md dark:border-white/10 dark:bg-white/[0.04]">
      <div className="flex items-start justify-between gap-3">
        <div>
          <p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-500 dark:text-zinc-500">{label}</p>
          <p className="mt-3 text-3xl font-semibold tracking-tight text-slate-950 dark:text-white">{value}</p>
          <p className="mt-2 text-sm text-slate-500 dark:text-zinc-400">{helper}</p>
        </div>
        <span className={cn("mt-1 inline-flex h-3 w-3 rounded-full shadow-[0_0_22px_currentColor]", accent)} />
      </div>
    </div>
  );
}

function SignalTile({
  icon: Icon,
  label,
  value,
  helper,
  tone
}: {
  icon: React.ComponentType<{ className?: string }>;
  label: string;
  value: string;
  helper: string;
  tone: string;
}) {
  return (
    <Card className="rounded-[28px] border border-slate-200/80 bg-white/92 p-5 shadow-[0_18px_50px_rgba(15,23,42,0.07)] dark:border-white/10 dark:bg-slate-950/72">
      <div className="flex items-start justify-between gap-3">
        <div>
          <p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-500 dark:text-zinc-400">{label}</p>
          <p className="mt-3 text-3xl font-semibold tracking-tight text-slate-950 dark:text-white">{value}</p>
          <p className="mt-2 text-sm text-slate-500 dark:text-zinc-400">{helper}</p>
        </div>
        <div className={cn("flex h-12 w-12 items-center justify-center rounded-2xl text-white shadow-lg", tone)}>
          <Icon className="h-5 w-5" />
        </div>
      </div>
    </Card>
  );
}

function InsightPill({ children }: { children: React.ReactNode }) {
  return (
    <div className="rounded-full border border-white/80 bg-white/80 px-3 py-2 text-xs font-medium text-slate-600 shadow-sm dark:border-white/10 dark:bg-white/[0.04] dark:text-zinc-300">
      {children}
    </div>
  );
}

export function DashboardView() {
  const sheets = useBusinessStore((state) => state.sheets);
  const alerts = useBusinessStore((state) => state.alerts);
  const isLoaded = useBusinessStore((state) => state.isLoaded);
  const error = useBusinessStore((state) => state.error);
  const [activeTab, setActiveTab] = useState<DashboardTab>("revenue");
  const [meetHistory, setMeetHistory] = useState<MeetSessionRecord[]>([]);
  const [aiInsight, setAiInsight] = useState("");
  const [aiError, setAiError] = useState("");
  const [isAiLoading, setIsAiLoading] = useState(false);
  const [ceoReport, setCeoReport] = useState("");
  const [ceoError, setCeoError] = useState("");
  const [isCeoLoading, setIsCeoLoading] = useState(false);

  useEffect(() => {
    setMeetHistory(readMeetHistory());
  }, []);

  useEffect(() => {
    if (!isLoaded) return;

    const requestDashboardAI = async (prompt: string) => {
      const response = await fetch("/api/ai/chat", {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          prompt,
          pathname: "/dashboard",
          meetHistory
        })
      });

      const payload = (await response.json()) as { error?: string; message?: string };
      if (!response.ok || !payload.message) {
        throw new Error(payload.error ?? "AI analysis is unavailable right now.");
      }

      return payload.message;
    };

    const loadExecutiveInsight = async () => {
      setIsAiLoading(true);
      setAiError("");
      setIsCeoLoading(true);
      setCeoError("");

      try {
        const [executive, weekly] = await Promise.all([
          requestDashboardAI(
            "Give me a boardroom-quality executive analysis of the full workspace. Cover projects, collections, revenue, pending amounts, leads, services, content, team, shopping, timetable, meetings, servers, and databases. Focus on what matters most right now."
          ),
          requestDashboardAI(
            "Write a weekly CEO report from the full workspace. Cover wins, risks, growth signals, delivery risks, collections, pipeline health, team capacity, and top next moves."
          )
        ]);

        setAiInsight(executive);
        setCeoReport(weekly);
      } catch (nextError) {
        const message = nextError instanceof Error ? nextError.message : "AI analysis is unavailable right now.";
        setAiError(message);
        setCeoError(message);
      } finally {
        setIsAiLoading(false);
        setIsCeoLoading(false);
      }
    };

    void loadExecutiveInsight();
  }, [isLoaded, meetHistory]);

  const projects = sheets.projects?.rows ?? [];
  const leads = sheets.leads?.rows ?? [];
  const revenueRows = sheets.revenue?.rows ?? [];
  const contentRows = sheets.content?.rows ?? [];
  const shoppingRows = sheets.shopping?.rows ?? [];
  const serviceRows = sheets.services?.rows ?? [];
  const serverRows = sheets.servers?.rows ?? [];
  const databaseRows = sheets.databases?.rows ?? [];
  const meetCount = meetHistory.length;

  const monthlyRevenue = buildMonthlyRevenue(sheets);
  const leadStatus = buildLeadStatusData(sheets);
  const serviceDemand = buildServiceDemandData(sheets);
  const teamCapacity = buildTeamCapacityData(sheets);
  const infrastructure = buildInfrastructureStatusData(sheets);
  const revenueMix = buildRevenueByCategory(sheets).slice(0, 5);

  const totalProjectValue = projects.reduce((sum, row) => sum + Number(row.projectValue ?? 0), 0);
  const totalReceived = projects.reduce((sum, row) => sum + Number(row.amountReceived ?? 0), 0);
  const totalPending = projects.reduce((sum, row) => sum + Number(row.pendingAmount ?? 0), 0);
  const totalExpenses = revenueRows
    .filter((row) => ["Expense", "Payroll", "Personal Use"].includes(String(row.entryType ?? "")))
    .reduce((sum, row) => sum + Number(row.amount ?? 0), 0);
  const netRevenue = totalReceived - totalExpenses;

  const convertedLeads = leads.filter((lead) => String(lead.leadStatus ?? "") === "Converted").length;
  const proposalLeads = leads.filter((lead) => String(lead.leadStatus ?? "") === "Proposal Sent").length;
  const activeProjects = projects.filter((project) => String(project.projectStatus ?? "") === "In Progress").length;
  const completedProjects = projects.filter((project) => String(project.projectStatus ?? "") === "Completed").length;
  const healthyServers = serverRows.filter((server) => String(server.status ?? "") === "Healthy").length;
  const openShopping = shoppingRows.filter((item) => !["Bought", "Deferred"].includes(String(item.purchaseStatus ?? ""))).length;
  const scheduledContent = contentRows.filter((item) => ["Scheduled", "Posted"].includes(String(item.stage ?? ""))).length;

  const collectionEfficiency = percent(totalReceived, totalProjectValue);
  const conversionRate = percent(convertedLeads, leads.length);
  const deliveryRate = percent(completedProjects, projects.length);
  const infraHealth = percent(healthyServers, Math.max(serverRows.length, 1));

  const projectStatusData = useMemo(() => {
    const statusCount = new Map<string, number>();
    projects.forEach((project) => {
      const status = String(project.projectStatus ?? "Not Started") || "Not Started";
      statusCount.set(status, (statusCount.get(status) ?? 0) + 1);
    });
    return Array.from(statusCount.entries()).map(([name, value]) => ({ name, value }));
  }, [projects]);

  const collectionByProject = useMemo(() => {
    return projects
      .map((project) => ({
        name: String(project.projectName ?? "Project"),
        received: Number(project.amountReceived ?? 0),
        pending: Number(project.pendingAmount ?? 0),
        value: Number(project.projectValue ?? 0)
      }))
      .filter((project) => project.value > 0 || project.received > 0 || project.pending > 0)
      .sort((left, right) => right.value - left.value)
      .slice(0, 8);
  }, [projects]);

  const leadValueData = useMemo(() => {
    return leads
      .map((lead) => ({
        name: String(lead.businessName ?? lead.contactName ?? "Lead"),
        value: Number(lead.expectedValue ?? 0)
      }))
      .filter((lead) => lead.value > 0)
      .sort((left, right) => right.value - left.value)
      .slice(0, 6);
  }, [leads]);

  const contentStageData = useMemo(() => {
    const stages = new Map<string, number>();
    contentRows.forEach((row) => {
      const stage = String(row.stage ?? "Unstaged") || "Unstaged";
      stages.set(stage, (stages.get(stage) ?? 0) + 1);
    });
    return Array.from(stages.entries()).map(([name, value]) => ({ name, value }));
  }, [contentRows]);

  const alertSummary = useMemo(() => {
    const count = { high: 0, medium: 0, low: 0 };
    alerts.forEach((alert) => {
      count[alert.severity] += 1;
    });
    return [
      { name: "High", value: count.high },
      { name: "Medium", value: count.medium },
      { name: "Low", value: count.low }
    ];
  }, [alerts]);

  const timetableLoadByDay = useMemo(() => {
    return assistantWeekdays.map((dayKey) => ({
      day: assistantWeekdayShortLabels[dayKey],
      value: (sheets.timetable?.rows ?? []).filter((row) => String(row[dayKey] ?? "").trim() !== "").length
    }));
  }, [sheets.timetable?.rows]);

  const now = new Date();
  const currentWeekStart = startOfDay(addDays(now, -6));
  const nextDay = startOfDay(addDays(now, 1));
  const previousWeekStart = startOfDay(addDays(currentWeekStart, -7));

  const currentWeekRevenue = revenueRows
    .filter(
      (row) =>
        String(row.entryType ?? "") === "Income" &&
        !isAutoRevenueSummaryRow(row) &&
        isInRange(String(row.entryDate ?? ""), currentWeekStart, nextDay)
    )
    .reduce((sum, row) => sum + Number(row.amount ?? 0), 0);
  const previousWeekRevenue = revenueRows
    .filter(
      (row) =>
        String(row.entryType ?? "") === "Income" &&
        !isAutoRevenueSummaryRow(row) &&
        isInRange(String(row.entryDate ?? ""), previousWeekStart, currentWeekStart)
    )
    .reduce((sum, row) => sum + Number(row.amount ?? 0), 0);

  const currentWeekPipeline = projects
    .filter((row) => isInRange(String(row.startDate ?? row.deliveryDate ?? ""), currentWeekStart, nextDay))
    .reduce((sum, row) => sum + Number(row.projectValue ?? 0), 0);
  const previousWeekPipeline = projects
    .filter((row) => isInRange(String(row.startDate ?? row.deliveryDate ?? ""), previousWeekStart, currentWeekStart))
    .reduce((sum, row) => sum + Number(row.projectValue ?? 0), 0);

  const currentWeekMeetings = meetHistory.filter((record) => isInRange(record.createdAt, currentWeekStart, nextDay)).length;
  const previousWeekMeetings = meetHistory.filter((record) => isInRange(record.createdAt, previousWeekStart, currentWeekStart)).length;

  const currentWeekContent = contentRows.filter((row) => isInRange(String(row.publishDate ?? ""), currentWeekStart, nextDay)).length;
  const previousWeekContent = contentRows.filter((row) => isInRange(String(row.publishDate ?? ""), previousWeekStart, currentWeekStart)).length;

  const comparisonCards = [
    {
      label: "Revenue This Week",
      value: formatCurrency(currentWeekRevenue),
      helper: "Real income entries in the last 7 days",
      trend: getTrend(currentWeekRevenue, previousWeekRevenue)
    },
    {
      label: "Signed This Week",
      value: formatCurrency(currentWeekPipeline),
      helper: "New project value entering delivery",
      trend: getTrend(currentWeekPipeline, previousWeekPipeline)
    },
    {
      label: "Meetings This Week",
      value: `${currentWeekMeetings}`,
      helper: "Client sessions created in workspace",
      trend: getTrend(currentWeekMeetings, previousWeekMeetings)
    },
    {
      label: "Content Scheduled",
      value: `${currentWeekContent}`,
      helper: "Planned publishing items this week",
      trend: getTrend(currentWeekContent, previousWeekContent)
    }
  ];

  const pressureBoard = useMemo(() => {
    return [
      {
        label: "Collections waiting",
        value: `${projects.filter((project) => Number(project.pendingAmount ?? 0) > 0).length}`,
        helper: `${formatCurrency(totalPending)} outstanding`
      },
      {
        label: "Proposal-stage leads",
        value: `${proposalLeads}`,
        helper: "Immediate conversion opportunity"
      },
      {
        label: "Content scheduled",
        value: `${scheduledContent}`,
        helper: "Publishing engine in motion"
      },
      {
        label: "Shopping queue",
        value: `${openShopping}`,
        helper: "Open company/personal purchases"
      }
    ];
  }, [projects, totalPending, proposalLeads, scheduledContent, openShopping]);

  const topRisks = useMemo(() => {
    const pendingProjects = projects
      .filter((project) => Number(project.pendingAmount ?? 0) > 0)
      .sort((left, right) => Number(right.pendingAmount ?? 0) - Number(left.pendingAmount ?? 0))
      .slice(0, 3)
      .map((project) => ({
        title: String(project.projectName ?? "Project"),
        detail: `${formatCurrency(Number(project.pendingAmount ?? 0))} still pending`
      }));

    const infraWarnings = serverRows
      .filter((server) => ["Warning", "Down"].includes(String(server.status ?? "")))
      .slice(0, 2)
      .map((server) => ({
        title: String(server.serverName ?? "Server"),
        detail: `Infra status: ${String(server.status ?? "Warning")}`
      }));

    return [...pendingProjects, ...infraWarnings].slice(0, 5);
  }, [projects, serverRows]);

  const todaysFollowUps = useMemo(() => {
    return leads.filter((lead) => isInRange(String(lead.followUpDate ?? ""), startOfDay(now), nextDay));
  }, [leads, now, nextDay]);

  const todaysTimetableLoad = useMemo(() => {
    const dayKeys = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"] as const;
    const key = dayKeys[now.getDay()];
    return (sheets.timetable?.rows ?? []).filter((row) => String(row[key] ?? "").trim() !== "").length;
  }, [now, sheets.timetable?.rows]);

  const todayPriorities = useMemo(() => {
    const priorities = [];

    if (todaysFollowUps.length > 0) {
      priorities.push({
        title: `${todaysFollowUps.length} lead follow-up${todaysFollowUps.length === 1 ? "" : "s"} due today`,
        detail: todaysFollowUps.slice(0, 3).map((lead) => String(lead.businessName ?? lead.contactName ?? "Lead")).join(", "),
        tone: "border-cyan-200 bg-cyan-50/80 dark:border-cyan-500/20 dark:bg-cyan-500/10"
      });
    }

    if (totalPending > 0) {
      priorities.push({
        title: `Collect ${formatCurrency(totalPending)} in pending payments`,
        detail: `${projects.filter((project) => Number(project.pendingAmount ?? 0) > 0).length} projects still need collections`,
        tone: "border-amber-200 bg-amber-50/80 dark:border-amber-500/20 dark:bg-amber-500/10"
      });
    }

    if (alerts.length > 0) {
      priorities.push({
        title: `${alerts.length} operational alert${alerts.length === 1 ? "" : "s"} waiting`,
        detail: alerts.slice(0, 2).map((alert) => alert.title).join(", "),
        tone: "border-rose-200 bg-rose-50/80 dark:border-rose-500/20 dark:bg-rose-500/10"
      });
    }

    if (todaysTimetableLoad === 0) {
      priorities.push({
        title: "Today's timetable is still empty",
        detail: "No work blocks are planned yet for today",
        tone: "border-violet-200 bg-violet-50/80 dark:border-violet-500/20 dark:bg-violet-500/10"
      });
    }

    if (scheduledContent === 0) {
      priorities.push({
        title: "No content is scheduled",
        detail: "Publishing pipeline needs fresh output",
        tone: "border-slate-200 bg-slate-50/80 dark:border-white/10 dark:bg-white/[0.03]"
      });
    }

    return priorities.slice(0, 5);
  }, [todaysFollowUps, totalPending, projects, alerts, todaysTimetableLoad, scheduledContent]);

  const anomalies = useMemo(() => {
    const nextAnomalies: Array<{ title: string; detail: string }> = [];

    if (totalProjectValue > 0 && totalPending / totalProjectValue > 0.45) {
      nextAnomalies.push({
        title: "Pending cash is unusually high",
        detail: `${percent(totalPending, totalProjectValue)}% of signed value is still uncollected`
      });
    }

    if (proposalLeads >= 3 && convertedLeads === 0) {
      nextAnomalies.push({
        title: "Proposal volume is not converting",
        detail: `${proposalLeads} proposal-stage leads are open without conversions yet`
      });
    }

    if (serverRows.some((server) => ["Warning", "Down"].includes(String(server.status ?? "")))) {
      nextAnomalies.push({
        title: "Infrastructure instability detected",
        detail: `${serverRows.filter((server) => ["Warning", "Down"].includes(String(server.status ?? ""))).length} servers need attention`
      });
    }

    if (openShopping >= 6) {
      nextAnomalies.push({
        title: "Shopping backlog is building up",
        detail: `${openShopping} items are still sitting in the purchase queue`
      });
    }

    if (netRevenue < 0) {
      nextAnomalies.push({
        title: "Net revenue is below zero",
        detail: "Expense outflow is currently outpacing realized collections"
      });
    }

    return nextAnomalies.slice(0, 4);
  }, [totalProjectValue, totalPending, proposalLeads, convertedLeads, serverRows, openShopping, netRevenue]);

  const aiGuidance = useMemo(() => {
    const guidance: Array<{ title: string; detail: string; tone: string }> = [];

    if (totalPending > 0) {
      guidance.push({
        title: "Collections follow-up should be automated first",
        detail: `${formatCurrency(totalPending)} is still pending across ${projects.filter((project) => Number(project.pendingAmount ?? 0) > 0).length} projects.`,
        tone: "border-amber-200 bg-amber-50/80 dark:border-amber-500/20 dark:bg-amber-500/10"
      });
    }

    if (todaysFollowUps.length > 0) {
      guidance.push({
        title: "Lead follow-up queue is ready for guided outreach",
        detail: `${todaysFollowUps.length} leads are due today and can be turned into scripted call or WhatsApp follow-ups.`,
        tone: "border-cyan-200 bg-cyan-50/80 dark:border-cyan-500/20 dark:bg-cyan-500/10"
      });
    }

    if (scheduledContent === 0) {
      guidance.push({
        title: "AI can help restart the content pipeline",
        detail: "No content is scheduled, so content ideas and post drafts should be generated from current services and active leads.",
        tone: "border-violet-200 bg-violet-50/80 dark:border-violet-500/20 dark:bg-violet-500/10"
      });
    }

    if (serverRows.some((server) => ["Warning", "Down"].includes(String(server.status ?? "")))) {
      guidance.push({
        title: "Infrastructure issue summaries should be surfaced daily",
        detail: `${serverRows.filter((server) => ["Warning", "Down"].includes(String(server.status ?? ""))).length} server items need AI-assisted prioritization.`,
        tone: "border-rose-200 bg-rose-50/80 dark:border-rose-500/20 dark:bg-rose-500/10"
      });
    }

    if (collectionEfficiency < 60 && totalProjectValue > 0) {
      guidance.push({
        title: "Revenue realization is lagging signed value",
        detail: `Only ${collectionEfficiency}% of signed project value is collected, so invoice reminders and payment nudges should be automated.`,
        tone: "border-emerald-200 bg-emerald-50/80 dark:border-emerald-500/20 dark:bg-emerald-500/10"
      });
    }

    return guidance.slice(0, 4);
  }, [todaysFollowUps, totalPending, projects, scheduledContent, serverRows, collectionEfficiency, totalProjectValue]);

  const displayCoverage = useMemo(() => {
    return [
      { label: "Projects", value: `${projects.length}`, helper: `showing top ${Math.min(collectionByProject.length, 8)} in cash view` },
      { label: "Leads", value: `${leads.length}`, helper: `showing top ${Math.min(leadValueData.length, 6)} in value view` },
      { label: "Content", value: `${contentRows.length}`, helper: `${contentStageData.length} active publishing stages` },
      { label: "Infrastructure", value: `${serverRows.length + databaseRows.length}`, helper: `${serverRows.length} servers, ${databaseRows.length} databases` }
    ];
  }, [projects.length, collectionByProject.length, leads.length, leadValueData.length, contentRows.length, contentStageData.length, serverRows.length, databaseRows.length]);

  return (
    <div className="space-y-6">
      <Card className="overflow-hidden rounded-[36px] border border-white/70 bg-[radial-gradient(circle_at_top_left,rgba(34,197,94,0.12),transparent_22%),radial-gradient(circle_at_top_right,rgba(59,130,246,0.12),transparent_26%),linear-gradient(135deg,rgba(255,255,255,0.96),rgba(248,250,252,0.88))] p-6 shadow-[0_30px_100px_rgba(15,23,42,0.10)] dark:border-white/10 dark:bg-[radial-gradient(circle_at_top_left,rgba(45,212,191,0.12),transparent_24%),radial-gradient(circle_at_top_right,rgba(59,130,246,0.14),transparent_28%),linear-gradient(135deg,rgba(9,9,11,0.92),rgba(24,24,27,0.85))]">
        <div className="grid gap-5 xl:grid-cols-[1.45fr_1fr]">
          <div className="space-y-5">
            <div className="flex flex-wrap items-start justify-between gap-4">
              <div>
                <p className="text-[11px] font-semibold uppercase tracking-[0.24em] text-slate-500 dark:text-zinc-400">
                  Executive Control Tower
                </p>
                <h1 className="mt-3 text-4xl font-semibold tracking-tight text-slate-950 dark:text-white">
                  Business intelligence, not just a dashboard
                </h1>
                <p className="mt-3 max-w-3xl text-sm leading-7 text-slate-600 dark:text-zinc-300">
                  This surface pulls real signals from projects, leads, collections, services, team operations, content, timetable, meetings, shopping, servers, and databases so you can act fast without reading every sheet.
                </p>
              </div>
              <div className="flex flex-wrap gap-2">
                <InsightPill>Projects: {projects.length}</InsightPill>
                <InsightPill>Leads: {leads.length}</InsightPill>
                <InsightPill>Meetings: {meetCount}</InsightPill>
                <InsightPill>Infra Assets: {serverRows.length + databaseRows.length}</InsightPill>
              </div>
            </div>

            {!isLoaded ? (
              <div className="rounded-[24px] border border-cyan-200 bg-cyan-50/80 px-4 py-3 text-sm text-cyan-800 dark:border-cyan-500/20 dark:bg-cyan-500/10 dark:text-cyan-200">
                Loading your live business data...
              </div>
            ) : null}

            {error ? (
              <div className="rounded-[24px] border border-rose-200 bg-rose-50/80 px-4 py-3 text-sm text-rose-700 dark:border-rose-500/20 dark:bg-rose-500/10 dark:text-rose-200">
                {error}
              </div>
            ) : null}

            <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
              <HeroMetric label="Total Project Value" value={formatCurrency(totalProjectValue)} helper="Signed business under management" accent="bg-cyan-500 text-cyan-500" />
              <HeroMetric label="Collections Realized" value={formatCurrency(totalReceived)} helper={`${collectionEfficiency}% of signed value collected`} accent="bg-emerald-500 text-emerald-500" />
              <HeroMetric label="Pending Exposure" value={formatCurrency(totalPending)} helper="Cash still waiting to be collected" accent="bg-amber-500 text-amber-500" />
              <HeroMetric label="Net Business Yield" value={formatCurrency(netRevenue)} helper="Collections minus expense outflow" accent="bg-violet-500 text-violet-500" />
            </div>

            <div className="grid gap-4 xl:grid-cols-[1.2fr_0.9fr]">
              <div className="rounded-[30px] border border-white/80 bg-white/72 p-5 shadow-sm backdrop-blur-md dark:border-white/10 dark:bg-white/[0.04]">
                <div className="flex items-center justify-between gap-3">
                  <div>
                    <p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-500 dark:text-zinc-500">Project Pulse</p>
                    <p className="mt-1 text-sm text-slate-500 dark:text-zinc-400">Signed value, received cash, and pending exposure in one view</p>
                  </div>
                  <span className="rounded-full border border-slate-200 bg-slate-50 px-3 py-1 text-xs font-semibold text-slate-600 dark:border-white/10 dark:bg-white/[0.03] dark:text-zinc-300">
                    {projects.length} tracked
                  </span>
                </div>
                {collectionByProject.length > 0 ? (
                  <div className="mt-4 h-[220px]">
                    <ResponsiveContainer width="100%" height="100%">
                      <BarChart data={collectionByProject.slice(0, 5)}>
                        <CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,0.16)" />
                        <XAxis dataKey="name" tickLine={false} axisLine={false} stroke="#64748b" hide />
                        <YAxis tickLine={false} axisLine={false} stroke="#64748b" tickFormatter={(value) => formatNumber(value)} />
                        <Tooltip contentStyle={tooltipStyle} formatter={(value: number) => formatCurrency(value)} />
                        <Bar dataKey="value" fill="#cbd5e1" radius={[10, 10, 0, 0]} />
                        <Bar dataKey="received" fill="#0f766e" radius={[10, 10, 0, 0]} />
                        <Bar dataKey="pending" fill="#d97706" radius={[10, 10, 0, 0]} />
                      </BarChart>
                    </ResponsiveContainer>
                  </div>
                ) : (
                  <div className="mt-4">
                    <EmptyVisual label="Project pulse will appear once project values and collections are added." />
                  </div>
                )}
              </div>

              <div className="rounded-[30px] border border-white/80 bg-white/72 p-5 shadow-sm backdrop-blur-md dark:border-white/10 dark:bg-white/[0.04]">
                <div className="flex items-center justify-between gap-3">
                  <div>
                    <p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-500 dark:text-zinc-500">Timetable Load</p>
                    <p className="mt-1 text-sm text-slate-500 dark:text-zinc-400">Weekly planning density across your timetable</p>
                  </div>
                  <span className="rounded-full border border-slate-200 bg-slate-50 px-3 py-1 text-xs font-semibold text-slate-600 dark:border-white/10 dark:bg-white/[0.03] dark:text-zinc-300">
                    {timetableLoadByDay.reduce((sum, item) => sum + item.value, 0)} filled
                  </span>
                </div>
                {timetableLoadByDay.some((item) => item.value > 0) ? (
                  <div className="mt-4 h-[220px]">
                    <ResponsiveContainer width="100%" height="100%">
                      <BarChart data={timetableLoadByDay}>
                        <CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,0.16)" />
                        <XAxis dataKey="day" tickLine={false} axisLine={false} stroke="#64748b" />
                        <YAxis tickLine={false} axisLine={false} stroke="#64748b" />
                        <Tooltip contentStyle={tooltipStyle} />
                        <Bar dataKey="value" fill="#2563eb" radius={[10, 10, 0, 0]} />
                      </BarChart>
                    </ResponsiveContainer>
                  </div>
                ) : (
                  <div className="mt-4">
                    <EmptyVisual label="Timetable distribution will show after daily slots are planned." />
                  </div>
                )}
              </div>
            </div>
          </div>

          <div className="grid gap-4">
            <div className="rounded-[30px] border border-white/80 bg-white/72 p-5 shadow-sm backdrop-blur-md dark:border-white/10 dark:bg-white/[0.04]">
              <p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-500 dark:text-zinc-500">Operating Efficiency</p>
              <div className="mt-4 grid gap-3 sm:grid-cols-3 xl:grid-cols-1">
                {[
                  { label: "Lead conversion", value: `${conversionRate}%`, helper: `${convertedLeads} leads converted` },
                  { label: "Delivery closure", value: `${deliveryRate}%`, helper: `${completedProjects}/${projects.length || 0} completed` },
                  { label: "Infra health", value: `${infraHealth}%`, helper: `${healthyServers}/${serverRows.length || 0} healthy` }
                ].map((item) => (
                  <div key={item.label} className="rounded-[22px] border border-slate-200/70 bg-slate-50/80 px-4 py-4 dark:border-white/10 dark:bg-white/[0.03]">
                    <div className="flex items-center justify-between gap-3">
                      <div>
                        <p className="text-sm font-semibold text-slate-900 dark:text-white">{item.label}</p>
                        <p className="mt-1 text-xs text-slate-500 dark:text-zinc-400">{item.helper}</p>
                      </div>
                      <span className="text-2xl font-semibold tracking-tight text-slate-950 dark:text-white">{item.value}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="rounded-[30px] border border-white/80 bg-white/72 p-5 shadow-sm backdrop-blur-md dark:border-white/10 dark:bg-white/[0.04]">
              <p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-500 dark:text-zinc-500">Pressure Board</p>
              <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-2">
                {pressureBoard.map((item) => (
                  <div key={item.label} className="rounded-[22px] border border-slate-200/70 bg-slate-50/80 px-4 py-4 dark:border-white/10 dark:bg-white/[0.03]">
                    <p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500 dark:text-zinc-500">{item.label}</p>
                    <p className="mt-2 text-2xl font-semibold tracking-tight text-slate-950 dark:text-white">{item.value}</p>
                    <p className="mt-1 text-xs text-slate-500 dark:text-zinc-400">{item.helper}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </Card>

      <div className="grid gap-4 xl:grid-cols-4">
        <SignalTile icon={BriefcaseBusiness} label="Active Projects" value={`${activeProjects}`} helper="Currently being delivered" tone="bg-gradient-to-br from-cyan-500 to-blue-600" />
        <SignalTile icon={CircleDollarSign} label="Received" value={formatCurrency(totalReceived)} helper="Collected across all projects" tone="bg-gradient-to-br from-emerald-500 to-teal-600" />
        <SignalTile icon={Wallet} label="Pending" value={formatCurrency(totalPending)} helper="Immediate cash collection target" tone="bg-gradient-to-br from-amber-500 to-orange-600" />
        <SignalTile icon={Activity} label="Net Revenue" value={formatCurrency(netRevenue)} helper="Live profit picture after outflow" tone="bg-gradient-to-br from-violet-500 to-fuchsia-600" />
      </div>

      <div className="grid gap-4 xl:grid-cols-[1.35fr_0.9fr]">
        <SectionCard
          title="AI Executive Analysis"
          subtitle="Workspace-wide reading across every sheet and operational signal"
          action={
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={async () => {
                setIsAiLoading(true);
                setAiError("");
                try {
                  const response = await fetch("/api/ai/chat", {
                    method: "POST",
                    headers: {
                      "Content-Type": "application/json"
                    },
                    body: JSON.stringify({
                      prompt:
                        "Refresh the executive analysis for the full business workspace. Summarize momentum, risks, bottlenecks, automation gaps, and the highest-leverage next moves.",
                      pathname: "/dashboard",
                      meetHistory: readMeetHistory()
                    })
                  });

                  const payload = (await response.json()) as { error?: string; message?: string };
                  if (!response.ok || !payload.message) {
                    throw new Error(payload.error ?? "AI analysis is unavailable right now.");
                  }
                  setAiInsight(payload.message);
                } catch (nextError) {
                  setAiError(nextError instanceof Error ? nextError.message : "AI analysis is unavailable right now.");
                } finally {
                  setIsAiLoading(false);
                }
              }}
              className="rounded-2xl"
            >
              <RefreshCw className={cn("mr-2 h-4 w-4", isAiLoading ? "animate-spin" : "")} />
              Refresh AI
            </Button>
          }
        >
          <div className="grid gap-4 xl:grid-cols-[1.2fr_0.9fr]">
            <div className="rounded-[26px] border border-slate-200/80 bg-slate-50/70 p-4 dark:border-white/10 dark:bg-white/[0.03]">
              <div className="flex items-start gap-4">
                <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-violet-500 to-cyan-500 text-white shadow-lg">
                  <Sparkles className="h-5 w-5" />
                </div>
                <div className="min-w-0">
                  <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-500 dark:text-zinc-500">AI Narrative</p>
                  <p className="mt-3 max-w-4xl text-sm leading-8 text-slate-600 dark:text-zinc-300">
                    {isAiLoading
                      ? "Analyzing the latest business data across projects, leads, revenue, content, team, shopping, timetable, meetings, and infrastructure..."
                      : aiInsight || "Add GEMINI_API_KEY in .env.local to unlock the AI executive readout here."}
                  </p>
                </div>
              </div>
            </div>

            <div className="grid gap-3">
              <div className="rounded-[26px] border border-slate-200/80 bg-slate-50/70 p-4 dark:border-white/10 dark:bg-white/[0.03]">
                <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-500 dark:text-zinc-500">AI Opportunity Hints</p>
                <div className="mt-3 grid gap-3">
                  {aiGuidance.length > 0 ? (
                    aiGuidance.map((item) => (
                      <div key={item.title} className={cn("rounded-[20px] border px-3 py-3", item.tone)}>
                        <p className="text-sm font-semibold text-slate-900 dark:text-white">{item.title}</p>
                        <p className="mt-1 text-xs leading-6 text-slate-600 dark:text-zinc-300">{item.detail}</p>
                      </div>
                    ))
                  ) : (
                    <div className="rounded-[20px] border border-slate-200 bg-white px-3 py-3 text-sm text-slate-500 dark:border-white/10 dark:bg-white/[0.03] dark:text-zinc-400">
                      Add more real operating data and AI opportunity hints will appear here.
                    </div>
                  )}
                </div>
              </div>

              <div className="rounded-[26px] border border-slate-200/80 bg-slate-50/70 p-4 dark:border-white/10 dark:bg-white/[0.03]">
                <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-500 dark:text-zinc-500">Display Coverage</p>
                <div className="mt-3 grid gap-2 sm:grid-cols-2">
                  {displayCoverage.map((item) => (
                    <div key={item.label} className="rounded-[18px] border border-slate-200 bg-white px-3 py-3 dark:border-white/10 dark:bg-white/[0.03]">
                      <p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-slate-500 dark:text-zinc-500">{item.label}</p>
                      <p className="mt-2 text-2xl font-semibold tracking-tight text-slate-950 dark:text-white">{item.value}</p>
                      <p className="mt-1 text-xs text-slate-500 dark:text-zinc-400">{item.helper}</p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
          {aiError ? (
            <div className="mt-4 rounded-[22px] border border-amber-200 bg-amber-50/80 px-4 py-3 text-sm text-amber-700 dark:border-amber-500/20 dark:bg-amber-500/10 dark:text-amber-200">
              {aiError}
            </div>
          ) : null}
        </SectionCard>

        <SectionCard title="Today's Priorities" subtitle="A command-center view of what deserves action first">
          <div className="grid gap-4">
            <div className="grid gap-3">
              {todayPriorities.length > 0 ? (
                todayPriorities.map((item, index) => (
                  <div key={`${item.title}-${index}`} className={cn("rounded-[24px] border px-4 py-4", item.tone)}>
                    <div className="flex items-start justify-between gap-3">
                      <div className="flex items-start gap-3">
                        <div className="mt-0.5 flex h-9 w-9 items-center justify-center rounded-2xl bg-white/80 text-slate-700 dark:bg-white/10 dark:text-zinc-100">
                          <CalendarClock className="h-4 w-4" />
                        </div>
                        <div>
                          <p className="text-sm font-semibold text-slate-900 dark:text-white">{item.title}</p>
                          <p className="mt-1 text-xs leading-6 text-slate-600 dark:text-zinc-300">{item.detail}</p>
                        </div>
                      </div>
                      <ArrowUpRight className="mt-1 h-4 w-4 text-slate-400" />
                    </div>
                  </div>
                ))
              ) : (
                <div className="rounded-[24px] border border-slate-200/80 bg-slate-50/80 px-4 py-5 text-sm text-slate-500 dark:border-white/10 dark:bg-white/[0.03] dark:text-zinc-400">
                  The daily board is clear right now. No urgent operational priorities are waiting.
                </div>
              )}
            </div>

            <div className="rounded-[24px] border border-slate-200/80 bg-slate-50/70 p-4 dark:border-white/10 dark:bg-white/[0.03]">
              <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-500 dark:text-zinc-500">Anomaly Callouts</p>
              <div className="mt-3 max-h-[320px] space-y-3 overflow-y-auto pr-1">
                {anomalies.length > 0 ? (
                  anomalies.map((item) => (
                    <div key={item.title} className="flex items-start gap-3 rounded-[20px] border border-slate-200 bg-white px-3 py-3 dark:border-white/10 dark:bg-white/[0.03]">
                      <div className="mt-0.5 flex h-8 w-8 items-center justify-center rounded-2xl bg-rose-500/10 text-rose-600 dark:text-rose-300">
                        <AlertTriangle className="h-4 w-4" />
                      </div>
                      <div>
                        <p className="text-sm font-semibold text-slate-900 dark:text-white">{item.title}</p>
                        <p className="mt-1 text-xs leading-6 text-slate-500 dark:text-zinc-400">{item.detail}</p>
                      </div>
                    </div>
                  ))
                ) : (
                  <div className="rounded-[20px] border border-slate-200 bg-white px-3 py-3 text-sm text-slate-500 dark:border-white/10 dark:bg-white/[0.03] dark:text-zinc-400">
                    No unusual swings are standing out right now.
                  </div>
                )}
              </div>
            </div>
          </div>
        </SectionCard>
      </div>

      <SectionCard
        title="This Week vs Last Week"
        subtitle="Short-term movement across cash, pipeline, meetings, and publishing"
      >
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
          {comparisonCards.map((item) => (
            <ComparisonCard key={item.label} label={item.label} value={item.value} helper={item.helper} trend={item.trend} />
          ))}
        </div>
      </SectionCard>

      <SectionCard
        title="Boardroom Drilldown"
        subtitle="Switch between financial, sales, operations, and infrastructure views"
        action={
          <div className="flex flex-wrap gap-2">
            {[
              { key: "revenue", label: "Revenue" },
              { key: "sales", label: "Sales" },
              { key: "operations", label: "Operations" },
              { key: "infrastructure", label: "Infrastructure" }
            ].map((tab) => (
              <button
                key={tab.key}
                type="button"
                onClick={() => setActiveTab(tab.key as DashboardTab)}
                className={cn(
                  "rounded-full border px-4 py-2 text-xs font-semibold uppercase tracking-[0.16em] transition",
                  activeTab === tab.key
                    ? "border-slate-900 bg-slate-900 text-white dark:border-white dark:bg-white dark:text-slate-950"
                    : "border-slate-200 bg-white text-slate-600 hover:border-slate-300 hover:text-slate-900 dark:border-white/10 dark:bg-white/[0.03] dark:text-zinc-300 dark:hover:border-white/20 dark:hover:text-white"
                )}
              >
                {tab.label}
              </button>
            ))}
          </div>
        }
      >
        {activeTab === "revenue" ? (
          <div className="space-y-4">
            <div className="grid gap-4 xl:grid-cols-[1.6fr_1fr]">
              <SectionCard title="Revenue command view" subtitle="Monthly collections against signed project value" className="shadow-none">
                {monthlyRevenue.length > 0 ? (
                  <div className="h-[400px]">
                    <ResponsiveContainer width="100%" height="100%">
                      <AreaChart data={monthlyRevenue}>
                        <defs>
                          <linearGradient id="receivedArea" x1="0" y1="0" x2="0" y2="1">
                            <stop offset="0%" stopColor="#0f766e" stopOpacity={0.45} />
                            <stop offset="100%" stopColor="#0f766e" stopOpacity={0.05} />
                          </linearGradient>
                          <linearGradient id="targetArea" x1="0" y1="0" x2="0" y2="1">
                            <stop offset="0%" stopColor="#2563eb" stopOpacity={0.26} />
                            <stop offset="100%" stopColor="#2563eb" stopOpacity={0.04} />
                          </linearGradient>
                        </defs>
                        <CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,0.18)" />
                        <XAxis dataKey="month" tickLine={false} axisLine={false} stroke="#64748b" />
                        <YAxis tickLine={false} axisLine={false} stroke="#64748b" tickFormatter={(value) => formatNumber(value)} />
                        <Tooltip contentStyle={tooltipStyle} formatter={(value: number) => formatCurrency(value)} />
                        <Area type="monotone" dataKey="target" stroke="#2563eb" fill="url(#targetArea)" strokeWidth={2} />
                        <Area type="monotone" dataKey="revenue" stroke="#0f766e" fill="url(#receivedArea)" strokeWidth={3} />
                      </AreaChart>
                    </ResponsiveContainer>
                  </div>
                ) : (
                  <EmptyVisual label="Add project dates and values to see monthly revenue intelligence." />
                )}
              </SectionCard>

              <SectionCard title="Portfolio composition" subtitle="Delivery mix and status shape" className="shadow-none">
                {projectStatusData.length > 0 ? (
                  <div className="grid h-[400px] gap-4 lg:grid-rows-[1fr_auto]">
                    <ResponsiveContainer width="100%" height="100%">
                      <PieChart>
                        <Pie data={projectStatusData} dataKey="value" nameKey="name" innerRadius={82} outerRadius={128} paddingAngle={3}>
                          {projectStatusData.map((entry, index) => (
                            <Cell key={entry.name} fill={COLORS[index % COLORS.length]} />
                          ))}
                        </Pie>
                        <Tooltip contentStyle={tooltipStyle} />
                      </PieChart>
                    </ResponsiveContainer>
                    <div className="grid gap-2">
                      {projectStatusData.map((item, index) => (
                        <div key={item.name} className="flex items-center justify-between rounded-2xl border border-slate-200 bg-slate-50/80 px-3 py-2 text-sm dark:border-white/10 dark:bg-white/[0.03]">
                          <div className="flex items-center gap-2">
                            <span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: COLORS[index % COLORS.length] }} />
                            <span className="text-slate-700 dark:text-zinc-200">{item.name}</span>
                          </div>
                          <span className="font-medium text-slate-900 dark:text-white">{item.value}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                ) : (
                  <EmptyVisual label="Project status visuals will appear once projects are added." />
                )}
              </SectionCard>
            </div>

            <div className="grid gap-4 xl:grid-cols-[1.1fr_0.9fr]">
              <SectionCard title="Collections by project" subtitle="Cash locked inside open accounts" className="shadow-none">
                {collectionByProject.length > 0 ? (
                  <div className="h-[340px]">
                    <ResponsiveContainer width="100%" height="100%">
                      <BarChart data={collectionByProject} layout="vertical" margin={{ left: 12, right: 8 }}>
                        <CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,0.16)" />
                        <XAxis type="number" tickLine={false} axisLine={false} stroke="#64748b" tickFormatter={(value) => formatNumber(value)} />
                        <YAxis dataKey="name" type="category" width={112} tickLine={false} axisLine={false} stroke="#64748b" />
                        <Tooltip contentStyle={tooltipStyle} formatter={(value: number) => formatCurrency(value)} />
                        <Bar dataKey="received" stackId="collections" fill="#0f766e" radius={[0, 8, 8, 0]} />
                        <Bar dataKey="pending" stackId="collections" fill="#d97706" radius={[0, 8, 8, 0]} />
                      </BarChart>
                    </ResponsiveContainer>
                  </div>
                ) : (
                  <EmptyVisual label="Project collection analytics will appear after project values are entered." />
                )}
              </SectionCard>

              <SectionCard title="Revenue mix" subtitle="Category contribution to signed business" className="shadow-none">
                {revenueMix.length > 0 ? (
                  <div className="h-[340px]">
                    <ResponsiveContainer width="100%" height="100%">
                      <PieChart>
                        <Pie data={revenueMix} dataKey="value" nameKey="name" innerRadius={72} outerRadius={112}>
                          {revenueMix.map((item, index) => (
                            <Cell key={item.name} fill={COLORS[index % COLORS.length]} />
                          ))}
                        </Pie>
                        <Tooltip contentStyle={tooltipStyle} formatter={(value: number) => formatCurrency(value)} />
                      </PieChart>
                    </ResponsiveContainer>
                  </div>
                ) : (
                  <EmptyVisual label="Revenue mix appears when project categories are filled." />
                )}
              </SectionCard>
            </div>
          </div>
        ) : null}

        {activeTab === "sales" ? (
          <div className="grid gap-4 xl:grid-cols-[1.1fr_1fr_1fr]">
            <SectionCard title="Lead conversion engine" subtitle="Stage count and value concentration" className="shadow-none">
              {leadStatus.length > 0 || leadValueData.length > 0 ? (
                <div className="grid gap-4">
                  <div className="h-[180px]">
                    <ResponsiveContainer width="100%" height="100%">
                      <BarChart data={leadStatus}>
                        <CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,0.16)" />
                        <XAxis dataKey="stage" tickLine={false} axisLine={false} stroke="#64748b" />
                        <YAxis tickLine={false} axisLine={false} stroke="#64748b" />
                        <Tooltip contentStyle={tooltipStyle} />
                        <Bar dataKey="value" radius={[12, 12, 0, 0]} fill="#7c3aed" />
                      </BarChart>
                    </ResponsiveContainer>
                  </div>
                  <div className="h-[140px]">
                    <ResponsiveContainer width="100%" height="100%">
                      <BarChart data={leadValueData}>
                        <CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,0.16)" />
                        <XAxis dataKey="name" tickLine={false} axisLine={false} stroke="#64748b" hide />
                        <YAxis tickLine={false} axisLine={false} stroke="#64748b" tickFormatter={(value) => formatNumber(value)} />
                        <Tooltip contentStyle={tooltipStyle} formatter={(value: number) => formatCurrency(value)} />
                        <Bar dataKey="value" radius={[12, 12, 0, 0]} fill="#2563eb" />
                      </BarChart>
                    </ResponsiveContainer>
                  </div>
                </div>
              ) : (
                <EmptyVisual label="Lead analytics will appear after leads are added." />
              )}
            </SectionCard>

            <SectionCard title="Service momentum" subtitle="Demand compared with delivery output" className="shadow-none">
              {serviceDemand.length > 0 ? (
                <div className="h-[340px]">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={serviceDemand}>
                      <CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,0.16)" />
                      <XAxis dataKey="name" tickLine={false} axisLine={false} stroke="#64748b" />
                      <YAxis tickLine={false} axisLine={false} stroke="#64748b" />
                      <Tooltip contentStyle={tooltipStyle} />
                      <Bar dataKey="leads" fill="#06b6d4" radius={[10, 10, 0, 0]} />
                      <Bar dataKey="projects" fill="#0f766e" radius={[10, 10, 0, 0]} />
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              ) : (
                <EmptyVisual label="Service analytics will appear once services are entered." />
              )}
            </SectionCard>

            <SectionCard title="Collections focus" subtitle="Where conversion should turn into cash next" className="shadow-none">
              <div className="grid max-h-[340px] gap-3 overflow-y-auto pr-1">
                {topRisks.length > 0 ? (
                  topRisks.map((item) => (
                    <div key={item.title} className="rounded-[22px] border border-slate-200 bg-slate-50/80 px-4 py-4 dark:border-white/10 dark:bg-white/[0.03]">
                      <p className="text-sm font-semibold text-slate-900 dark:text-white">{item.title}</p>
                      <p className="mt-1 text-xs leading-6 text-slate-500 dark:text-zinc-400">{item.detail}</p>
                    </div>
                  ))
                ) : (
                  <EmptyVisual label="Cash and risk priorities appear once project and infra data are available." />
                )}
              </div>
            </SectionCard>
          </div>
        ) : null}

        {activeTab === "operations" ? (
          <div className="grid gap-4 xl:grid-cols-[1fr_1fr_1fr]">
            <SectionCard title="Team capacity" subtitle="Availability-weighted execution bandwidth" className="shadow-none">
              {teamCapacity.length > 0 ? (
                <div className="h-[300px]">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={teamCapacity}>
                      <CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,0.16)" />
                      <XAxis dataKey="name" tickLine={false} axisLine={false} stroke="#64748b" />
                      <YAxis tickLine={false} axisLine={false} stroke="#64748b" />
                      <Tooltip contentStyle={tooltipStyle} />
                      <Bar dataKey="capacity" fill="#0f766e" radius={[10, 10, 0, 0]} />
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              ) : (
                <EmptyVisual label="Team utilization appears once team members are added." />
              )}
            </SectionCard>

            <SectionCard title="Content pipeline" subtitle="Publishing stage distribution" className="shadow-none">
              {contentStageData.length > 0 ? (
                <div className="h-[300px]">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={contentStageData}>
                      <CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,0.16)" />
                      <XAxis dataKey="name" tickLine={false} axisLine={false} stroke="#64748b" />
                      <YAxis tickLine={false} axisLine={false} stroke="#64748b" />
                      <Tooltip contentStyle={tooltipStyle} />
                      <Bar dataKey="value" fill="#7c3aed" radius={[10, 10, 0, 0]} />
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              ) : (
                <EmptyVisual label="Content stage analytics appear when content rows are added." />
              )}
            </SectionCard>

            <SectionCard title="Execution pressure" subtitle="Daily throughput across schedule and purchases" className="shadow-none">
              <div className="grid gap-3">
                {[
                  { label: "Today's follow-ups", value: `${todaysFollowUps.length}`, helper: "Leads that need a call today" },
                  { label: "Today's timetable load", value: `${todaysTimetableLoad}`, helper: "Filled work blocks in today's planner" },
                  { label: "Open shopping items", value: `${openShopping}`, helper: "Purchases still waiting to be closed" },
                  { label: "Scheduled content", value: `${scheduledContent}`, helper: "Items already in the publishing queue" }
                ].map((item) => (
                  <div key={item.label} className="rounded-[22px] border border-slate-200 bg-slate-50/80 px-4 py-4 dark:border-white/10 dark:bg-white/[0.03]">
                    <p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-slate-500 dark:text-zinc-500">{item.label}</p>
                    <p className="mt-2 text-3xl font-semibold tracking-tight text-slate-950 dark:text-white">{item.value}</p>
                    <p className="mt-1 text-xs text-slate-500 dark:text-zinc-400">{item.helper}</p>
                  </div>
                ))}
              </div>
            </SectionCard>
          </div>
        ) : null}

        {activeTab === "infrastructure" ? (
          <div className="grid gap-4 xl:grid-cols-[1fr_1fr]">
            <SectionCard title="Risk radar" subtitle="Alerts and infrastructure watchlist" className="shadow-none">
              <div className="grid gap-3">
                <div className="grid grid-cols-3 gap-2">
                  {alertSummary.map((item, index) => (
                    <div key={item.name} className="rounded-[20px] border border-slate-200 bg-slate-50/80 px-3 py-4 text-center dark:border-white/10 dark:bg-white/[0.03]">
                      <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-500 dark:text-zinc-400">{item.name}</p>
                      <p className="mt-2 text-2xl font-semibold text-slate-950 dark:text-white">{item.value}</p>
                      <span className="mt-2 inline-flex h-2.5 w-2.5 rounded-full" style={{ backgroundColor: COLORS[(index + 3) % COLORS.length] }} />
                    </div>
                  ))}
                </div>
                <div className="grid gap-2">
                  {infrastructure.map((item, index) => (
                    <div key={item.name} className="flex items-center justify-between rounded-[20px] border border-slate-200 bg-slate-50/80 px-3 py-3 text-sm dark:border-white/10 dark:bg-white/[0.03]">
                      <div className="flex items-center gap-2">
                        <AlertTriangle className="h-4 w-4" style={{ color: COLORS[index % COLORS.length] }} />
                        <span className="text-slate-700 dark:text-zinc-200">{item.name}</span>
                      </div>
                      <span className="font-semibold text-slate-950 dark:text-white">{item.value}</span>
                    </div>
                  ))}
                </div>
              </div>
            </SectionCard>

            <SectionCard title="Infrastructure posture" subtitle="Servers and databases under current management" className="shadow-none">
              <div className="grid gap-3">
                {[
                  { label: "Servers", value: `${serverRows.length}`, helper: `${healthyServers} healthy right now` },
                  { label: "Databases", value: `${databaseRows.length}`, helper: "Tracked production and internal data stores" },
                  { label: "Infra alerts", value: `${serverRows.filter((server) => ["Warning", "Down"].includes(String(server.status ?? ""))).length}`, helper: "Systems that need intervention" },
                  { label: "Meet sessions", value: `${meetCount}`, helper: "Client communication activity logged" }
                ].map((item) => (
                  <div key={item.label} className="rounded-[22px] border border-slate-200 bg-slate-50/80 px-4 py-4 dark:border-white/10 dark:bg-white/[0.03]">
                    <p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-slate-500 dark:text-zinc-500">{item.label}</p>
                    <p className="mt-2 text-3xl font-semibold tracking-tight text-slate-950 dark:text-white">{item.value}</p>
                    <p className="mt-1 text-xs text-slate-500 dark:text-zinc-400">{item.helper}</p>
                  </div>
                ))}
              </div>
            </SectionCard>
          </div>
        ) : null}
      </SectionCard>

      <SectionCard
        title="Weekly CEO Report"
        subtitle="Auto-generated leadership summary across the full business workspace"
        action={
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={async () => {
              setIsCeoLoading(true);
              setCeoError("");
              try {
                const response = await fetch("/api/ai/chat", {
                  method: "POST",
                  headers: {
                    "Content-Type": "application/json"
                  },
                  body: JSON.stringify({
                    prompt:
                      "Refresh the weekly CEO report from the entire workspace. Cover wins, blockers, financial movement, delivery risk, pipeline quality, team load, and the top 3 next moves.",
                    pathname: "/dashboard",
                    meetHistory: readMeetHistory()
                  })
                });

                const payload = (await response.json()) as { error?: string; message?: string };
                if (!response.ok || !payload.message) {
                  throw new Error(payload.error ?? "Weekly CEO report is unavailable right now.");
                }
                setCeoReport(payload.message);
              } catch (nextError) {
                setCeoError(nextError instanceof Error ? nextError.message : "Weekly CEO report is unavailable right now.");
              } finally {
                setIsCeoLoading(false);
              }
            }}
            className="rounded-2xl"
          >
            <RefreshCw className={cn("mr-2 h-4 w-4", isCeoLoading ? "animate-spin" : "")} />
            Refresh Report
          </Button>
        }
      >
        <div className="grid gap-4 xl:grid-cols-[1.25fr_0.9fr]">
          <div className="rounded-[28px] border border-slate-200/80 bg-slate-50/70 p-5 dark:border-white/10 dark:bg-white/[0.03]">
            <p className="text-sm leading-8 text-slate-600 dark:text-zinc-300">
              {isCeoLoading
                ? "Preparing the weekly CEO report from projects, leads, revenue, team, content, shopping, timetable, meetings, and infrastructure..."
                : ceoReport || "Add GEMINI_API_KEY in .env.local to unlock the automated weekly CEO report."}
            </p>
          </div>
          <div className="grid gap-3">
            {[
              { label: "Lead conversion", value: `${conversionRate}%`, icon: Target },
              { label: "Collections realized", value: `${collectionEfficiency}%`, icon: CircleDollarSign },
              { label: "Infra health", value: `${infraHealth}%`, icon: CheckCircle2 },
              { label: "Open priorities", value: `${alerts.length + openShopping}`, icon: AlertTriangle }
            ].map((item) => (
              <div key={item.label} className="flex items-center justify-between rounded-[24px] border border-slate-200 bg-white px-4 py-4 shadow-sm dark:border-white/10 dark:bg-white/[0.03]">
                <div className="flex items-center gap-3">
                  <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-slate-100 text-slate-700 dark:bg-white/[0.05] dark:text-zinc-200">
                    <item.icon className="h-4 w-4" />
                  </div>
                  <span className="text-sm font-medium text-slate-700 dark:text-zinc-200">{item.label}</span>
                </div>
                <span className="text-xl font-semibold text-slate-950 dark:text-white">{item.value}</span>
              </div>
            ))}
          </div>
        </div>
        {ceoError ? (
          <div className="mt-4 rounded-[22px] border border-amber-200 bg-amber-50/80 px-4 py-3 text-sm text-amber-700 dark:border-amber-500/20 dark:bg-amber-500/10 dark:text-amber-200">
            {ceoError}
          </div>
        ) : null}
      </SectionCard>
    </div>
  );
}
